language: node_js
dist: trusty
sudo: required
env:
  global:
    - HUGO_BASEURL=https://fieldguide.documenters.org/
node_js:
  - '8'
branches:
  only:
    - master
before_install:
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install apt-transport-https azure-cli
  - az login -u $AZ_LOGIN_NAME -p $AZ_PASSWORD --service-principal --tenant $AZ_TENANT > /dev/null 2>&1
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  - provider: script
    script: az storage blob upload-batch -s ./dist/ -d "https://documentersguide.blob.core.windows.net/\$web"
  - provider: script
    script: az cdn endpoint purge -g documenters -n documentersguide --profile-name documentersguide --content-paths '/*'
