baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Documenters Field Guide"
enableRobotsTXT = true

[params]
  subtitle = "Field guide site"
  description = "Field guide for Documenters program"
  author = "City Bureau"

[menu]
  [[menu.main]]
    identifier = "before-you-begin"
    name = "Before You Begin"
    url = "/before-you-begin/"
    weight = 1
  [[menu.main]]
    identifier = "attendance"
    name = "Attendance"
    url = "/attendance/"
    weight = 2
  [[menu.main]]
    identifier = "on-assignment"
    name = "On assignment"
    url = "/on-assignment/"
    weight = 3
  [[menu.main]]
    identifier = "going-public"
    name = "Going Public"
    url = "/going-public/"
    weight = 4
  [[menu.main]]
    name = "Freedom of Information Act Requests"
    parent = "going-public"
    url = "/going-public/foia/"
    weight = 20
  

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackFriday]
  hrefTargetBlank = true
