baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Documenters Field Guide"


[params]
  subtitle = "Field guide site"
  description = "Field guide for Documenters program"
  author = "City Bureau"

[menu]
  [[menu.main]]
    name = "Introduction"
    url = "/intro/"
    weight = -100

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
