baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Documenters Field Guide"
enableRobotsTXT = true

[params]
  subtitle = "Field guide site"
  description = "Field guide for Documenters program"
  author = "City Bureau"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackFriday]
  hrefTargetBlank = true
