baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Documenters Field Guide"


[params]
  subtitle = "Field guide site"
  description = "Field guide for Documenters program"
  author = "City Bureau"

[menu]
  [[menu.main]]
    identifier = "intro"
    name = "Introduction"
    url = "/intro/"
    weight = 1
  [[menu.main]]
    identifier = "before-you-begin"
    name = "Before You Begin"
    url = "/before-you-begin/"
    weight = 2
  [[menu.main]]
    name = "Illinois Governmental Flowchart"
    parent = "before-you-begin"
    url = "/before-you-begin/il-governmental-flowchart/"
    weight = 10
  [[menu.main]]
    name = "Finding Your Representative"
    parent = "before-you-begin"
    url = "/before-you-begin/finding-your-representative/"
    weight = 20
  [[menu.main]]
    name = "Finding Local Meetings"
    parent = "before-you-begin"
    url = "/before-you-begin/finding-local-meetings/"
    weight = 30
  [[menu.main]]
    name = "Pre-research"
    parent = "before-you-begin"
    url = "/before-you-begin/research/"
    weight = 40
  [[menu.main]]
    name = "Equipment Checklist"
    parent = "before-you-begin"
    url = "/before-you-begin/equipment-checklist/"
    weight = 50
  [[menu.main]]
    identifier = "attendance"
    name = "Attendance"
    url = "/attendance/"
    weight = 3
  [[menu.main]]
    name = "Open Meetings Act"
    parent = "attendance"
    url = "/attendance/open-meetings-act/"
    weight = 10
  [[menu.main]]
    name = "Recording Public Meetings"
    parent = "attendance"
    url = "/attendance/recording-public-meetings/"
    weight = 20
  [[menu.main]]
    name = "Identifiying yourself and addressing officials"
    parent = "attendance"
    url = "/attendance/identifying-addressing-officials/"
    weight = 30
  [[menu.main]]
    name = "Attendance Checklist"
    parent = "attendance"
    url = "/attendance/attendance-checklist/"
    weight = 40
  [[menu.main]]
    name = "Glossary of Terms"
    parent = "attendance"
    url = "/attendance/glossary/"
    weight = 50
  [[menu.main]]
    identifier = "on-assignment"
    name = "On assignment"
    url = "/on-assignment/"
    weight = 4
  [[menu.main]]
    name = "Notetaking"
    parent = "on-assignment"
    url = "/on-assignment/notetaking/"
    weight = 10
  [[menu.main]]
    name = "Interviewing"
    parent = "on-assignment"
    url = "/on-assignment/interviewing/"
    weight = 20
  [[menu.main]]
    name = "Web Research"
    parent = "on-assignment"
    url = "/on-assignment/web-research/"
    weight = 30
  [[menu.main]]
    name = "Live-tweeting"
    parent = "on-assignment"
    url = "/on-assignment/live-tweeting/"
    weight = 40
  [[menu.main]]
    name = "Mobile Photography and Video Recording"
    parent = "on-assignment"
    url = "/on-assignment/photo-video/"
    weight = 50
  [[menu.main]]
    name = "Mobile Audio Recording"
    parent = "on-assignment"
    url = "/on-assignment/audio/"
    weight = 60
  [[menu.main]]
    name = "Creating Tags"
    parent = "on-assignment"
    url = "/on-assignment/creating-tags/"
    weight = 70
  [[menu.main]]
    identifier = "going-public"
    name = "Going Public"
    url = "/going-public/"
    weight = 5
  [[menu.main]]
    name = "Curating your newsletter or blog"
    parent = "going-public"
    url = "/going-public/newsletter-blog/"
    weight = 10
  [[menu.main]]
    name = "Freedom of Information Act Requests"
    parent = "going-public"
    url = "/going-public/foia/"
    weight = 20
  [[menu.main]]
    name = "Working with your local newspaper"
    parent = "going-public"
    url = "/going-public/local-newspaper/"
    weight = 30
  [[menu.main]]
    name = "Reporting back"
    parent = "going-public"
    url = "/going-public/reporting-back/"
    weight = 40
  

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackFriday]
  hrefTargetBlank = true
