baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "Documenters Field Guide"
enableRobotsTXT = true

[params]
  subtitle = "Field guide site"
  description = "Field guide for Documenters program"
  author = "City Bureau"

[menu]
  [[menu.main]]
    identifier = "before-you-begin"
    name = "Before You Begin"
    url = "/before-you-begin/"
    weight = 1
  [[menu.main]]
    identifier = "on-assignment"
    name = "On assignment"
    url = "/on-assignment/"
    weight = 2
  [[menu.main]]
    identifier = "frequently-asked-questions"
    name = "Frequently Asked Questions"
    url = "/frequently-asked-questions/"
    weight = 3
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 5
  

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackFriday]
  hrefTargetBlank = true
