name: Deploy
on:
  push:
    branches:
      - master

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  HUGO_BASEURL: https://fieldguide.documenters.org/
  AZURE_STORAGE_ACCOUNT: documentersguide
  AZURE_CDN_PROFILE: documentersguide

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: yarn

    - run: yarn build

    - name: Deploy to Azure
      run: |
        az storage blob upload-batch -s ./dist/ -d '$web' --content-cache-control 'max-age=86400' --account-name $AZURE_STORAGE_ACCOUNT
        ls ./dist/assets/app.* | grep -v 'map$' | xargs basename | xargs -I % az storage blob upload -f ./dist/assets/% -c '$web' -n assets/% --content-cache-control 'max-age=31536000' --account-name $AZURE_STORAGE_ACCOUNT
        az storage blob upload -f ./dist/admin/config.yml -c '$web' -n admin/config.yml --content-type application/x-yaml --account-name $AZURE_STORAGE_ACCOUNT

    - name: Purge CDN
      run: |
        az cdn endpoint purge -g documenters -n $AZURE_STORAGE_ACCOUNT --profile-name $AZURE_CDN_PROFILE --content-paths "/"
        az cdn endpoint purge -g documenters -n $AZURE_STORAGE_ACCOUNT --profile-name $AZURE_CDN_PROFILE --content-paths "/*"
